channels:
  - conda-forge
dependencies:
  - python==3.11
  - wandb==0.15.12
  - networkx==3.2
  - pytorch==2.0
  - torchvision==0.15.2
  - numpy==1.25
  - sympy==1.12
  - argcomplete==3.1
  - tqdm==4.66
  - plotly==5.18
  - scikit-learn=1.3
  - ipykernel